# Generated by Django 6.0 on 2025-12-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
